aws_region: ap-northeast-1
aws_security_group: "my-minions-security-group"
aws_keypair_name: "my-minions-keypair"
aws_keypair_path: "./awskey.pem"

ec2_project_tag: "my-minions"
ec2_inventory_group: "myminionsmachines"

ec2_instances:
  - name: graviton2
    instance_type: t4g.small
    image: ami-0c706aa84dc076112
  - name: intel_xeon
    instance_type: t3.small
    image: ami-0590f3a1742b17914

benchmark_suite_repo: "https://github.com/xxuejie/ckb-vm-sysbench"
benchmark_suite_version: "HEAD"

benchmark_target_repo: "https://github.com/nervosnetwork/ckb-vm"
benchmark_target_version: "HEAD"
